<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="insert_drive_wheel_rim" params="base_name parent_name radius thickness spoke_width">

        <joint name="${base_name}_joint" type="fixed">
            <parent link="${parent_name}"/>
            <child link="${base_name}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <link name="${base_name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.3} ${thickness+0.001}"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0.1 0.1 1"/>
                </material>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.3} ${thickness+0.001}"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0.1 0.1 1"/>
                </material>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-pi/4}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.3} ${thickness+0.001}"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0.1 0.1 1"/>
                </material>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${pi/4}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.3} ${thickness+0.001}"/>
                </geometry>
                <material name="red">
                    <color rgba="1 0.1 0.1 1"/>
                </material>
            </visual>
        </link>

    </xacro:macro>

    
</robot>