# Example parameters for a UART connection to the Easy IMU module (i.e MPU9250 EIMU Module).
eimu_ros:
  ros__parameters:
    port: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:1.3:1.0-port0"
    # port: "/dev/ttyUSB0"
    frame_id: "imu"
    publish_frequency: 10.0
    eimu_reference_frame_id: 1  # 0 - NWU,  1 - ENU,  2 - NED
    publish_tf_on_map_frame: false